alias: "Helligkeit verringern mit Hue Tap Dial (Taste 1 + Drehen links)"
description: "Steuert die Lampe 'Dach-Lampe-TV' mit dem Hue Tap Dial Switch 'Dach-tap-dial' (Taste 1 + Drehen links)."
mode: single
trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/Dach-tap-dial/action"
    payload: "{\"action\":\"1_rotate_left\"}"
condition:
  - condition: mqtt
    topic: "zigbee2mqtt/Dach-tap-dial/action"
    payload: "{\"action\":\"1_hold\"}"
action:
  - service: light.turn_on
    target:
      entity_id: light.dach_lampe_tv
    data:
      brightness_step: -25
      transition: 0.1
  - delay: "0.1"
  - repeat:
      while:
        - condition: mqtt
          topic: "zigbee2mqtt/Dach-tap-dial/action"
          payload: "{\"action\":\"1_rotate_left\"}"
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.dach_lampe_tv
          data:
            brightness_step: -25
            transition: 0.1
        - delay: "0.1"