alias: "Lampe umschalten mit Hue Tap Dial (Taste 1 drücken)"
description: "Schaltet die Lampe 'Dach-Lampe-TV' mit dem Hue Tap Dial Switch 'Dach-tap-dial' (Taste 1 drücken)."
mode: single
trigger:
  - domain: mqtt
    device_id: afbc0fec6dfd2c36ba252295054f7188
    type: action
    subtype: button_1_press
    trigger: device
conditions: []
action:
  - type: toggle
    device_id: 5e76870ad2bad8e59760f9294b080047
    entity_id: 07929d8bb0087b3ad58a12fdad7c26d1
    domain: light