alias: "Lampe umschalten mit Hue Tap Dial (Taste 1 drücken)"
description: "Schaltet die Lampe 'Dach-Lampe-TV' mit dem Hue Tap Dial Switch 'Dach-tap-dial' (Taste 1 drücken)."
mode: single
trigger:
  - domain: mqtt
    device_id: afbc0fec6dfd2c36ba252295054f7188  # zigbee2mqtt/Dach-tap-dial
    type: action
    subtype: button_1_press_release
    trigger: device
conditions: []
action:
  - service: light.toggle
    target:
      device_id: 5e76870ad2bad8e59760f9294b080047  # zigbee2mqtt/Dach-Lampe-TV
      entity_id: light.dach_lampe_tv